version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: coverage-x-todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: todo
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: coverage-x-todo-backend
    environment:
      DB_DATABASE: todo
      DB_USER: root
      DB_PASSWORD: root123
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:
