version: '3.8'

services:
  mysql:
    image: mysql:9.0
    container_name: coverage-x-todo-mysql
    restart: always
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  coverage-x-todo-backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coverage-x-todo-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - springboot-mysql-network

volumes:
  mysql-data:

networks:
  springboot-mysql-network:
    driver: bridge