version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: coverage-x-todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: coverage-x-todo-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./env.properties:/app/env.properties

volumes:
  mysql_data:
